#!/usr/bin/env bash
# One-time Firebase setup for the eleven real-time tools.
#
# Order matters. The client code requires the current rules -- ownerUid on
# every session, authentication on every write -- so the rules have to be live
# before a real config reaches the deployed site. Paste the config first and
# the tools run against whatever rules the project currently has, which for a
# fresh project means "allow nothing" and for an older one may mean the open
# rules this replaced.
#
# Prerequisites this script cannot do for you, both interactive:
#   npx firebase login          OAuth consent on your Google account
#   two console toggles, flagged below
#
# Usage:  bash scripts/firebase-setup.sh <firebase-project-id>
set -euo pipefail

PROJECT="${1:-}"
if [ -z "$PROJECT" ]; then
  echo "usage: bash scripts/firebase-setup.sh <firebase-project-id>" >&2
  echo "       npx firebase projects:list   # to see yours" >&2
  exit 2
fi

FB="npx --yes firebase"

# Every collection the rules define. Kept in sync by the check below rather
# than by hand -- a collection missing a TTL keeps children's free text
# indefinitely, and nothing else in the repo would notice.
COLLECTIONS=(
  brainstormSessions challengeDeckSessions chiliChallengeSessions
  choiceBoardSessions exitTicketSessions growthWallSessions
  helpLadderSessions liveQuizSessions peerFeedbackSessions
  snowballSessions zonesSessions
)

RULES_FILE="packages/shell/firestore.rules"
IN_RULES=$(grep -oE "match /[a-zA-Z]+Sessions/" "$RULES_FILE" | sed 's|match /||;s|/||' | sort -u)
LISTED=$(printf '%s\n' "${COLLECTIONS[@]}" | sort -u)
if [ "$IN_RULES" != "$LISTED" ]; then
  echo "This script's collection list has drifted from $RULES_FILE:" >&2
  diff <(echo "$LISTED") <(echo "$IN_RULES") >&2 || true
  exit 1
fi

if ! $FB login:list 2>/dev/null | grep -qi '@'; then
  echo "Not signed in. Run:  npx firebase login" >&2
  exit 1
fi

echo "==> 1/3  Publishing Firestore rules to $PROJECT"
# This is the step a git push does not do. The rules live in the project, not
# in the repo; the file here is only the source of truth for what to publish.
$FB deploy --only firestore:rules --project "$PROJECT"

echo
echo "==> 2/3  Retention (30-day TTL on createdAt)"
if command -v gcloud >/dev/null 2>&1; then
  for c in "${COLLECTIONS[@]}"; do
    echo "    $c"
    gcloud firestore fields ttls update createdAt \
      --collection-group="$c" --project="$PROJECT" --async --quiet
  done
  echo "    TTL requested for ${#COLLECTIONS[@]} collections (applies asynchronously)."
else
  echo "    gcloud is not installed, so this cannot be scripted."
  echo "    Either install it (brew install --cask google-cloud-sdk, then"
  echo "    gcloud auth login) and re-run, or set it in the console:"
  echo "      Firestore -> each collection -> Collection Settings -> Time-to-live"
  echo "      field: createdAt, 30 days"
  echo "    Collections:"
  printf '      %s\n' "${COLLECTIONS[@]}"
fi

echo
echo "==> 3/3  Web config"
echo "    Writing packages/shell/firebase-config.js"
CONFIG=$($FB apps:sdkconfig WEB --project "$PROJECT" 2>/dev/null | sed -n '/{/,/}/p')
if [ -z "$CONFIG" ]; then
  echo "    No web app registered in this project. Create one with:" >&2
  echo "      npx firebase apps:create WEB \"Teacher Toolkit\" --project $PROJECT" >&2
  echo "    then re-run this script." >&2
  exit 1
fi
cat > packages/shell/firebase-config.js <<CFG
// Generated by scripts/firebase-setup.sh for project $PROJECT.
//
// Public by design: this identifies the project, it does not authorise
// anything. Security comes from packages/shell/firestore.rules, which are
// tested by \`npm run test:rules\`. Safe to commit.
window.TK_FIREBASE_CONFIG = $CONFIG;
CFG
echo "    done"

cat <<'NEXT'

Two things left that have no CLI and must be done in the console:

  1. Authentication -> Sign-in method -> enable Anonymous.
     Every write requires request.auth; without this the rules reject all of
     them and each tool shows a "check your connection" toast.

  2. Firestore Database -> create it, in production mode, if this is a new
     project.

Then, in the repo:

  - Narrow IGNORED_CONSOLE in tests/smoke.spec.mjs. It allowlists /firebase/i
    and /firestore/i, which was right while there was no config and now hides
    real errors.
  - Commit the generated firebase-config.js and push, so the deployed site
    gets it.
  - Open a teacher page and a student page and check a write lands. Nothing
    automated covers the real backend.
NEXT
